// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs1P4yM9hGlUriOSHpXMl38wGnYQBuz9A',
    appId: '1:980540770024:web:6ae1b6c4d1a99bbf71ab5d',
    messagingSenderId: '980540770024',
    projectId: 'trainingtask-cb343',
    authDomain: 'trainingtask-cb343.firebaseapp.com',
    databaseURL: 'https://trainingtask-cb343-default-rtdb.firebaseio.com',
    storageBucket: 'trainingtask-cb343.appspot.com',
    measurementId: 'G-MLETH62QKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDRGflBBH6Q1v51H3yBdqhM0SBk912Ai4',
    appId: '1:980540770024:android:20633987967b02b571ab5d',
    messagingSenderId: '980540770024',
    projectId: 'trainingtask-cb343',
    databaseURL: 'https://trainingtask-cb343-default-rtdb.firebaseio.com',
    storageBucket: 'trainingtask-cb343.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2GOP1u1jsuMFysC42asrn3nUAp-v_cs4',
    appId: '1:980540770024:ios:e2952ca4c691327d71ab5d',
    messagingSenderId: '980540770024',
    projectId: 'trainingtask-cb343',
    databaseURL: 'https://trainingtask-cb343-default-rtdb.firebaseio.com',
    storageBucket: 'trainingtask-cb343.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2GOP1u1jsuMFysC42asrn3nUAp-v_cs4',
    appId: '1:980540770024:ios:e2952ca4c691327d71ab5d',
    messagingSenderId: '980540770024',
    projectId: 'trainingtask-cb343',
    databaseURL: 'https://trainingtask-cb343-default-rtdb.firebaseio.com',
    storageBucket: 'trainingtask-cb343.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs1P4yM9hGlUriOSHpXMl38wGnYQBuz9A',
    appId: '1:980540770024:web:862003235cca9da571ab5d',
    messagingSenderId: '980540770024',
    projectId: 'trainingtask-cb343',
    authDomain: 'trainingtask-cb343.firebaseapp.com',
    databaseURL: 'https://trainingtask-cb343-default-rtdb.firebaseio.com',
    storageBucket: 'trainingtask-cb343.appspot.com',
    measurementId: 'G-8HY97J2WF2',
  );

}